[0.114s] Invoking command in '/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/sensor_interfaces -DCMAKE_INSTALL_PREFIX=/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/install/sensor_interfaces
[0.201s] -- Found ament_cmake: 1.3.2 (/opt/ros/humble/share/ament_cmake/cmake)
[1.540s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[1.553s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[1.577s] -- Found rosidl_adapter: 3.1.3 (/opt/ros/humble/share/rosidl_adapter/cmake)
[1.905s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[4.049s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[4.051s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[4.052s]   sensor_interfaces --arguments-file
[4.053s]   /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/rosidl_adapter__arguments__sensor_interfaces.json
[4.054s]   --output-dir
[4.055s]   /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/rosidl_adapter/sensor_interfaces
[4.056s]   --output-file
[4.057s]   /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/rosidl_adapter/sensor_interfaces.idls)
[4.059s]   returned error code 1:
[4.060s] 
[4.061s]   Traceback (most recent call last):
[4.062s] 
[4.064s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[4.065s]       return _run_code(code, main_globals, None,
[4.067s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[4.068s]       exec(code, run_globals)
[4.070s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[4.072s]       sys.exit(main())
[4.073s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[4.075s]       abs_idl_file = convert_to_idl(
[4.077s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[4.079s]       return convert_srv_to_idl(
[4.081s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[4.083s]       srv = parse_service_string(package_name, input_file.stem, content)
[4.085s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 850, in parse_service_string
[4.087s]       raise InvalidServiceSpecification(
[4.090s] 
[4.092s]   rosidl_adapter.parser.InvalidServiceSpecification: Could not find separator
[4.093s]   '---' between request and response
[4.094s] 
[4.095s] Call Stack (most recent call first):
[4.096s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[4.097s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[4.098s] 
[4.099s] [0m
[4.100s] -- Configuring incomplete, errors occurred!
[4.102s] See also "/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/CMakeFiles/CMakeOutput.log".
[4.108s] Invoked command in '/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces' returned '1': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/sensor_interfaces -DCMAKE_INSTALL_PREFIX=/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/install/sensor_interfaces
