Invoking command in '/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/build/sensor_data': PYTHONPATH=/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/install/sensor_data/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py develop --prefix /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/install/sensor_data --editable --build-directory /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/build/sensor_data/build --no-deps install_data --install-dir /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/install/sensor_data
Invoked command in '/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/build/sensor_data' returned '0': PYTHONPATH=/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/install/sensor_data/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py develop --prefix /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/install/sensor_data --editable --build-directory /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/build/sensor_data/build --no-deps install_data --install-dir /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/install/sensor_data
