[0.323s] Invoking command in '/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/install/sensor_data:/opt/ros/humble /usr/bin/cmake /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/sensor_interfaces -DCMAKE_INSTALL_PREFIX=/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/install/sensor_interfaces
[1.650s] -- Found ament_cmake: 1.3.2 (/opt/ros/humble/share/ament_cmake/cmake)
[4.130s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[4.177s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[4.223s] -- Found rosidl_adapter: 3.1.3 (/opt/ros/humble/share/rosidl_adapter/cmake)
[5.099s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[11.588s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[11.590s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[11.592s]   sensor_interfaces --arguments-file
[11.593s]   /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/rosidl_adapter__arguments__sensor_interfaces.json
[11.595s]   --output-dir
[11.596s]   /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/rosidl_adapter/sensor_interfaces
[11.598s]   --output-file
[11.599s]   /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/rosidl_adapter/sensor_interfaces.idls)
[11.601s]   returned error code 1:
[11.602s] 
[11.604s]   Traceback (most recent call last):
[11.605s] 
[11.606s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[11.608s]       return _run_code(code, main_globals, None,
[11.610s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[11.611s]       exec(code, run_globals)
[11.613s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[11.614s]       sys.exit(main())
[11.616s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[11.618s]       abs_idl_file = convert_to_idl(
[11.620s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[11.622s]       return convert_srv_to_idl(
[11.624s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[11.626s]       srv = parse_service_string(package_name, input_file.stem, content)
[11.628s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 850, in parse_service_string
[11.630s]       raise InvalidServiceSpecification(
[11.631s] 
[11.633s]   rosidl_adapter.parser.InvalidServiceSpecification: Could not find separator
[11.634s]   '---' between request and response
[11.635s] 
[11.636s] Call Stack (most recent call first):
[11.637s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[11.639s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[11.640s] 
[11.641s] [0m
[11.642s] -- Configuring incomplete, errors occurred!
[11.644s] See also "/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces/CMakeFiles/CMakeOutput.log".
[11.691s] Invoked command in '/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/build/sensor_interfaces' returned '1': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/install/sensor_data:/opt/ros/humble /usr/bin/cmake /home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/src/sensor_interfaces -DCMAKE_INSTALL_PREFIX=/home/pi/gps/Python-GPS-m8p-d/ros2_gps_ws/install/sensor_interfaces
